- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : Create Depolyment
    command : sudo kubectl create deployment appdeployment image=soumyaranjanrout0/medicure-image:v1

  - name : Deploy the depolyment to nodeport with two replica
    command : sudo kubectl expose deployment appdeployment --replicas=2 --port=8082 --type=NodePort
